-- CreateTable
CREATE TABLE "eventComments" (
    "commentId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "comment" STRING NOT NULL,
    "eventsEventId" INT4,

    CONSTRAINT "eventComments_pkey" PRIMARY KEY ("commentId")
);

-- CreateTable
CREATE TABLE "Contributor" (
    "contributorId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "contributions" STRING[],
    "userEmail" STRING NOT NULL,
    "eventsEventId" INT4,

    CONSTRAINT "Contributor_pkey" PRIMARY KEY ("contributorId")
);

-- CreateTable
CREATE TABLE "Participant" (
    "participantId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userEmail" STRING NOT NULL,

    CONSTRAINT "Participant_pkey" PRIMARY KEY ("participantId")
);

-- CreateTable
CREATE TABLE "Events" (
    "eventId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "description" STRING NOT NULL,
    "time" TIMESTAMP(3) NOT NULL,
    "city" STRING NOT NULL,
    "address" STRING NOT NULL,
    "eventTags" STRING[],
    "organizerEmail" STRING NOT NULL,
    "partId" INT4 NOT NULL,

    CONSTRAINT "Events_pkey" PRIMARY KEY ("eventId")
);

-- AddForeignKey
ALTER TABLE "eventComments" ADD CONSTRAINT "eventComments_eventsEventId_fkey" FOREIGN KEY ("eventsEventId") REFERENCES "Events"("eventId") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Contributor" ADD CONSTRAINT "Contributor_userEmail_fkey" FOREIGN KEY ("userEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Contributor" ADD CONSTRAINT "Contributor_eventsEventId_fkey" FOREIGN KEY ("eventsEventId") REFERENCES "Events"("eventId") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Participant" ADD CONSTRAINT "Participant_userEmail_fkey" FOREIGN KEY ("userEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Events" ADD CONSTRAINT "Events_organizerEmail_fkey" FOREIGN KEY ("organizerEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Events" ADD CONSTRAINT "Events_partId_fkey" FOREIGN KEY ("partId") REFERENCES "Participant"("participantId") ON DELETE RESTRICT ON UPDATE CASCADE;
