/*
  Warnings:

  - You are about to drop the `Comments` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "Comments" DROP CONSTRAINT "Comments_PostId_fkey";

-- DropForeignKey
ALTER TABLE "Comments" DROP CONSTRAINT "Comments_userEmail_fkey";

-- DropTable
DROP TABLE "Comments";

-- CreateTable
CREATE TABLE "postComments" (
    "commentId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "comment" STRING NOT NULL,
    "userEmail" STRING NOT NULL,
    "postsPostId" INT4,

    CONSTRAINT "postComments_pkey" PRIMARY KEY ("commentId")
);

-- AddForeignKey
ALTER TABLE "postComments" ADD CONSTRAINT "postComments_userEmail_fkey" FOREIGN KEY ("userEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "postComments" ADD CONSTRAINT "postComments_postsPostId_fkey" FOREIGN KEY ("postsPostId") REFERENCES "Posts"("postId") ON DELETE SET NULL ON UPDATE CASCADE;
