-- AlterTable
ALTER TABLE "User" ADD COLUMN     "ResourcePts" INT4 NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN     "WorkPts" INT4 NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE "Comments" (
    "commentId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "comment" STRING NOT NULL,
    "userEmail" STRING NOT NULL,
    "postsPostId" INT4,

    CONSTRAINT "Comments_pkey" PRIMARY KEY ("commentId")
);

-- CreateTable
CREATE TABLE "Posts" (
    "postId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "tags" STRING[],
    "content" STRING NOT NULL,
    "Likes" INT4 NOT NULL DEFAULT 0,
    "userEmail" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Posts_pkey" PRIMARY KEY ("postId")
);

-- AddForeignKey
ALTER TABLE "Comments" ADD CONSTRAINT "Comments_userEmail_fkey" FOREIGN KEY ("userEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Comments" ADD CONSTRAINT "Comments_postsPostId_fkey" FOREIGN KEY ("postsPostId") REFERENCES "Posts"("postId") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Posts" ADD CONSTRAINT "Posts_userEmail_fkey" FOREIGN KEY ("userEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;
