-- CreateTable
CREATE TABLE "User" (
    "firstName" STRING NOT NULL,
    "lastName" STRING NOT NULL,
    "email" STRING NOT NULL,
    "password" STRING NOT NULL,
    "image" STRING,
    "resourcePts" INT4 NOT NULL DEFAULT 0,
    "workPts" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "User_pkey" PRIMARY KEY ("email")
);

-- CreateTable
CREATE TABLE "postComments" (
    "commentId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "comment" STRING NOT NULL,
    "userEmail" STRING NOT NULL,
    "postsPostId" INT4 NOT NULL,

    CONSTRAINT "postComments_pkey" PRIMARY KEY ("commentId")
);

-- CreateTable
CREATE TABLE "Posts" (
    "postId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "tags" STRING[],
    "content" STRING NOT NULL,
    "userEmail" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "image" STRING,
    "likes" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "Posts_pkey" PRIMARY KEY ("postId")
);

-- CreateTable
CREATE TABLE "eventComments" (
    "commentId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "comment" STRING NOT NULL,
    "eventsEventId" INT4,
    "userEmail" STRING NOT NULL,

    CONSTRAINT "eventComments_pkey" PRIMARY KEY ("commentId")
);

-- CreateTable
CREATE TABLE "Contributor" (
    "contributorId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userEmail" STRING NOT NULL,
    "eventsEventId" INT4,
    "monetary" FLOAT8,

    CONSTRAINT "Contributor_pkey" PRIMARY KEY ("contributorId")
);

-- CreateTable
CREATE TABLE "Participant" (
    "participantId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userEmail" STRING NOT NULL,
    "eventsEventId" INT4 NOT NULL,

    CONSTRAINT "Participant_pkey" PRIMARY KEY ("participantId")
);

-- CreateTable
CREATE TABLE "Events" (
    "eventId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "description" STRING NOT NULL,
    "time" TIMESTAMP(3) NOT NULL,
    "city" STRING NOT NULL,
    "address" STRING NOT NULL,
    "eventTags" STRING[],
    "organizerEmail" STRING NOT NULL,
    "donationAmount" FLOAT8 NOT NULL DEFAULT 0.0,
    "image" STRING,
    "lat" FLOAT8 NOT NULL DEFAULT 0.0,
    "long" FLOAT8 NOT NULL DEFAULT 0.0,

    CONSTRAINT "Events_pkey" PRIMARY KEY ("eventId")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- AddForeignKey
ALTER TABLE "postComments" ADD CONSTRAINT "postComments_postsPostId_fkey" FOREIGN KEY ("postsPostId") REFERENCES "Posts"("postId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "postComments" ADD CONSTRAINT "postComments_userEmail_fkey" FOREIGN KEY ("userEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Posts" ADD CONSTRAINT "Posts_userEmail_fkey" FOREIGN KEY ("userEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "eventComments" ADD CONSTRAINT "eventComments_eventsEventId_fkey" FOREIGN KEY ("eventsEventId") REFERENCES "Events"("eventId") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "eventComments" ADD CONSTRAINT "eventComments_userEmail_fkey" FOREIGN KEY ("userEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Contributor" ADD CONSTRAINT "Contributor_eventsEventId_fkey" FOREIGN KEY ("eventsEventId") REFERENCES "Events"("eventId") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Contributor" ADD CONSTRAINT "Contributor_userEmail_fkey" FOREIGN KEY ("userEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Participant" ADD CONSTRAINT "Participant_eventsEventId_fkey" FOREIGN KEY ("eventsEventId") REFERENCES "Events"("eventId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Participant" ADD CONSTRAINT "Participant_userEmail_fkey" FOREIGN KEY ("userEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Events" ADD CONSTRAINT "Events_organizerEmail_fkey" FOREIGN KEY ("organizerEmail") REFERENCES "User"("email") ON DELETE RESTRICT ON UPDATE CASCADE;
